%include "xpcf/api/IComponentIntrospect.i"
%include "core/Messages.i"
%include "datastructure/GeometryDefinitions.i"
%include "datastructure/Keyframe.i"
%include "datastructure/Frame.i"
%include "datastructure/Keypoint.i"
%include "datastructure/DescriptorMatch.i"
%include "datastructure/CloudPoint.i"
%include "datastructure/Map.i"

%include "interfaces/api/solver/map/IMapper.h"
