%include "xpcf/api/IComponentIntrospect.i"
%include "core/Messages.i"
//%include "datastructure/GeometryDefinitions.i"
//%include "datastructure/MathDefinitions.i"
//%include "datastructure/Image.i"
//%include "datastructure/Keyframe.i"
//%include "datastructure/Keypoint.i"
//%include "datastructure/CloudPoint.i"
%include "datastructure/Keyframe.i"
%include "datastructure/DescriptorMatch.i"

%include "interfaces/api/solver/map/ITriangulator.h"
